language: python 
python:
- '2.7' 
sudo: false 
cache:
  directories:
  - "~/.platformio" 
env: - PLATFORMIO_CI_SRC=src/ 
install: 
- pip install -U platformio 
- platformio lib install 567 562 
script: 
- platformio run -e nodemcuv2 
deploy:
  provider: releases
  api_key:
    secure: ibW7/tKoWDIt3KJiP+q/iAhkDVwuT9grbek287Pwh50vAvIbIz5ztkcyV3HzF/j/UA/UXWpXC0yxzdG51CzxAUsza3DGCB+BqMmUYEHk31Htti012h/r4vKT1aS1Zo3B60$
  file: ".pioenvs/nodemcuv2/firmware.bin"
  on:
    repo: ArunmozhiRajavel/IoTCI
